apiVersion: v1
kind: ServiceAccount
metadata:
  name: slack-bot
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-bot
  namespace: monitoring
  labels:
    app: slack-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-bot
  template:
    metadata:
      labels:
        app: slack-bot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: slack-bot
      containers:
      - name: slack-bot
        image: ashcircle03/slack-bot:v1.0.1
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8000
          name: metrics
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: SLACK_BOT_TOKEN
        - name: SLACK_CHANNEL
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: SLACK_CHANNEL
        - name: METRICS_PORT
          value: "8000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: slack-bot
  namespace: monitoring
  labels:
    app: slack-bot
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: slack-bot