apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: discord-bot
        image: docker.io/ashcircle03/discord-bot:29  # ← 태그(예: latest, 1, ${BUILD_NUMBER}) 반드시 명시
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: metrics
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secret
              key: BOT_TOKEN
      imagePullSecrets:
      - name: dockerhub-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
