apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s/
    
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    
    [auth]
    disable_login_form = false
