# 슬랙 봇 시크릿 설정 가이드
# 
# 실제 사용 시, 아래 명령어로 시크릿을 생성하세요:
#
# kubectl create secret generic slack-bot-secrets \
#   --from-literal=bot-token="xoxb-your-slack-bot-token" \
#   --from-literal=signing-secret="your-slack-signing-secret" \
#   -n monitoring

apiVersion: v1
kind: Secret
metadata:
  name: slack-bot-secrets
  namespace: monitoring
type: Opaque
data:
  # Base64로 인코딩된 값들
  # bot-token: <your-base64-encoded-bot-token>
  # signing-secret: <your-base64-encoded-signing-secret>
  bot-token: eG94Yi15b3VyLXNsYWNrLWJvdC10b2tlbg==  # 예시 - 실제 토큰으로 교체하세요
  signing-secret: eW91ci1zbGFjay1zaWduaW5nLXNlY3JldA==     # 예시 - 실제 시크릿으로 교체하세요
