# Slack Webhook Secret for AlertManager
# 실제 사용 시, 아래 명령어로 시크릿을 생성하세요:
#
# kubectl create secret generic slack-webhook-secret \
#   --from-literal=webhook-url="https://hooks.slack.com/services/YOUR/WEBHOOK/URL" \
#   -n monitoring

apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: monitoring
type: Opaque
data:
  # Base64로 인코딩된 webhook URL
  # 실제 webhook URL을 base64로 인코딩하여 아래 값을 교체하세요
  # echo -n "https://hooks.slack.com/services/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" | base64
  webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA4UUJMTlVUQjQvQjA4VUZQUzVRVEQvVEdBSnBza3B6cXU2TUNPRVM4OGVKMklX
