apiVersion: v1
kind: Service
metadata:
  name: slack-bot
  namespace: monitoring
  labels:
    app: slack-bot
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: slack-bot
---
apiVersion: v1
kind: Service
metadata:
  name: slack-bot-nodeport
  namespace: monitoring
  labels:
    app: slack-bot
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
    name: http
  selector:
    app: slack-bot
