apiVersion: v1
kind: Service
metadata:
  name: discord-bot
  labels:
    app: discord-bot
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: discord-bot
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
